kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
  namespace: ${EKS_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 30Gi


