# Example StorageClass that adds labels to the AWS EBS.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: ${EKS_NAMESPACE}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer