apiVersion: v1
kind: Service
metadata:
  name: webapp1
  namespace: webapp
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: webapp1
  ports:
  - port: 25443
    targetPort: 25443