apiVersion: v1
kind: Namespace
metadata:
  name: webapp
  labels:
    name: webapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    name: linkerd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: webapp

